### ISSUE TITLE
Module parse failed: Unexpected character '@'

### ISSUE THREAD

**Issue by SpadeGod** [ant-design/babel-plugin-import#222] opened 2018-03-30 09:28 UTC
if i use the config  in .babelrc like this: 
`"plugins": [
    ["import", {
      "libraryName": "antd",
      "style": true
    }]
  ]` 
webpack throw error when  i  packaging

![image](https://user-images.githubusercontent.com/17895227/38132826-4bc78618-343f-11e8-9bb8-c303da61dbf6.png)

but if i drop the "plugins" config , its ok, why ? 

i used webpack4.1.1

the webpack.config.js is that

![image](https://user-images.githubusercontent.com/17895227/38133063-283c0e02-3440-11e8-9d1c-ab8223431819.png)

**Comment by SpadeGod** [comment] 2018-03-30 09:44
I think it nothing to do with less-loader, i try to install it and less, but alse throw another error .

wow , It's really a cursing problem

**Comment by tim-soft** [comment] 2018-03-30 21:13
@SpadeGod You might need to apply a PostCSS loader above sass-loader to inline require on those imports before passing the styles to css-loader

**Comment by SpadeGod** [comment] 2018-04-02 07:06
@tim-soft hi bro, thanks for your quick answer .  but im not very understand about how to use MiniCssExtractPlugin and what it can do. It seems that it has a lot of dependency on plug-ins. so i get another solution looks like a fool @-@. i use the less-loader first to compile less then compile other css、sass in other loader. but i think I may repeat the package. Do you have any better advice ？ thx
![image](https://user-images.githubusercontent.com/17895227/38186710-d70fbe5e-3686-11e8-9b85-9cac5f4641d6.png)
i will Strengthen understanding about PostCSS and MiniCssExtractPlugin if you highly recommend

**Comment by yesmeck** [comment] 2018-04-25 02:32
Closing since it's not a bug of `babel-plugin-import`

**Closed by yesmeck** 2018-04-25 02:32 UTC
